name: bioinformatics
channels:
- rdkit
- conda-forge
- defaults
dependencies:
    - libgcc=5.2.0
    - rdkit
    - pip
    - pip:
        - pandas==1.0.1
        - numpy==1.18.1
        - scikit-learn==0.22.2.post1
        - mordred
        - streamlit>=0.82.0
